back to starship for bash & zsh; exit 1 for exceptions in mntdev

diff --git a/.local/bin/mntdev b/.local/bin/mntdev
--- a/.local/bin/mntdev
+++ b/.local/bin/mntdev
@@ -17,12 +17,12 @@ umountAll(){
 		umountDev $whatd && success "Ntfs umounted"
 	elif lsblk | grep -q 'usb'; then
 		umountDev $whatd && success "Usb umounted"
-	else error "No drives found"; fi
+	else error "No drives found"; exit 1; fi
 }
 
 case "$1" in
 	-u) shift; mountUsb $1 ;;
 	-n) shift; ntfsMount $1 ;;
 	-o) shift; umountAll ;;
-	*) error "Invalid option"; echo "-u for usb\n-n for ntfs\n-o for umount" ;;
+	*) error "Invalid option"; echo "-u for usb\n-n for ntfs\n-o for umount"; exit 1 ;;
 esac
