organize and add winget support

diff --git a/.local/bin/pm b/.local/bin/pm
--- a/.local/bin/pm
+++ b/.local/bin/pm
@@ -6,34 +6,14 @@ if [ $# -lt 1 ]; then
 else
 	exist(){ command -v "$1" > /dev/null 2>&1 && return 0 || return 1; }
 
-	if [ -z "$DISTRO" ]; then
-		exp_distro(){ export DISTRO="$(grep -w $1 /etc/os-release | cut -d '=' -f 2)"; }
-		if grep -wq 'ID_LIKE' /etc/os-release; then
-			exp_distro 'ID_LIKE'
-		else
-			exp_distro 'ID'
-		fi
-	fi
-
-	if [ -z "$PERM" ]; then
-		if exist 'sudo'; then
-			PERM='sudo'
-		elif exist 'doas'; then
-			PERM='doas'
-		else
-			echo "Sudo | doas dosen't exist"
-			exit 1
-		fi
-	fi
-
 	case "$DISTRO" in
-		[Aa]rch ) pmn='pacman' ;pm="$PERM pacman" ;;
-		[Dd]ebian | [Uu]buntu ) pmn='apt' ;pm="$PERM apt" ;;
-		[Gg]entoo ) pmnt='emerge'; pm="$PERM emerge -avq" ;;
+		[Aa]rch ) pmn='pacman'; pm="$PERM $pmn" ;;
+		[Dd]ebian | [Uu]buntu ) pmn='apt'; pm="$PERM $pmn" ;;
+		[Gg]entoo ) pmnt='emerge'; pm="$PERM $pmn -avq" ;;
+		*suse* ) pmn='zypper'; pm="$PERM $pmn" ;;
 	esac
 
 	aur='paru'; fl='flatpak'; viewer='fzf';
-
 
 	exist 'flatpak'
 	is_flatpak=$?
@@ -41,6 +21,100 @@ else
 	is_paru=$?
 	exist 'rate-mirrors'
 	is_rate_mirrors=$?
+	exist 'nix'
+	is_nix=$?
+
+	if $WSL; then
+		win='winget.exe'
+		exist $win
+		is_win=$?
+	fi
+
+	install(){
+		case "$@" in
+			*.* ) flatpak_stuff i $@ ;;
+			* )
+				case "$pmn" in
+					'pacman' ) $pm -S $@ || aur i $@ ;;
+					'emerge' ) $pm $@ ;;
+					'apt' ) $pm install $@ ;;
+					'zypper') $pm install $@ ;;
+				esac
+				;;
+			esac
+	}
+
+	update(){
+		case "$pmn" in
+			'pacman' ) $pm -Syyu && aur u;;
+			'emerge' ) $pm --sync && $pm --update --deep --with-bdeps=y @world && $pm --depclean ;;
+			'apt' ) $pm update && $pm upgrade ;;
+			'zypper' ) $pm update ;;
+		esac
+		[ $is_flatpak -eq 0 ] && flatpak_stuff u
+	}
+
+	uninstall(){
+		case "$@" in
+			*.* ) flatpak_stuff r $@ ;;
+			* )
+				case "$pmn" in
+					'pacman' ) $pm -Rns $@ ;;
+					'emerge' ) $pm -c $@ ;;
+					'apt' ) $pm remove $@ ;;
+					'zypper' ) $pm remove $@ ;;
+				esac
+				;;
+		esac
+	}
+
+	list(){
+		case "$pmn" in
+			'pacman' ) $pmn -Q ;;
+			'emerge' ) equery list "*" ;;
+			'apt' ) dpkg-query -W | cut -f1 ;;
+			'zypper' ) $pmn search -i | cut -d '|' -f2 | tail -n +6 ;;
+		esac
+	}
+
+	count(){ list | wc -l; }
+
+	search(){
+		case "$pmn" in
+			'pacman' ) $pmn -Ss $1 || aur s $1 ;;
+			'emerge' ) $pm --search $1 ;;
+			'apt' ) $pmn search $1 ;;
+			'zypper' ) $pmn search $1 ;;
+		esac
+	}
+
+	remove_zombies(){
+		case "$pmn" in
+			'pacman' ) $pm -Rns $($pm -Qtdq) ;;
+			'emerge' ) gentoo_stuff nu && $pm --depclean ;;
+			'apt' ) $pm autoremove ;;
+		esac
+	}
+
+	edit_conf(){
+		case "$pmn" in
+			'pacman' ) $PERM $EDITOR /etc/pacman.conf ;;
+			'emerge' ) $PERM $EDITOR /etc/portage/make.conf ;;
+			'apt' ) $PERM $EDITOR /etc/apt/sources.list ;;
+		esac
+	}
+
+	auto_install_uninstall(){
+		for p in $@; do
+			if list | grep -q "$p"; then
+				to_uninstall="$to_uninstall $p"
+			else
+				to_install="$to_install $p"
+			fi
+		done
+		[ -n "$to_install" ] && install $to_install
+		[ -n "$to_uninstall" ] && uninstall $to_uninstall
+	}
 
 	aur(){
 		if exist 'pacman'; then
@@ -109,59 +183,6 @@ else
 		fi
 	}
 
-	install(){
-		case "$@" in
-			*.* ) flatpak_stuff i $@ ;;
-			* )
-				case "$pmn" in
-					'pacman' ) $pm -S $@ || aur i $@ ;;
-					'emerge' ) $pm $@ ;;
-					'apt' ) $pm install $@ ;;
-				esac
-				;;
-			esac
-	}
-
-	update(){
-		case "$pmn" in
-			'pacman' ) $pm -Syyu && aur u;;
-			'emerge' ) $pm --sync && $pm --update --deep --with-bdeps=y @world && $pm --depclean ;;
-			'apt' ) $pm update && $pm upgrade ;;
-		esac
-		[ $is_flatpak -eq 0 ] && flatpak_stuff u
-	}
-
-	uninstall(){
-		case "$@" in
-			*.* ) flatpak_stuff r $@ ;;
-			* )
-				case "$pmn" in
-					'pacman' ) $pm -Rns $@ ;;
-					'emerge' ) $pm -c $@ ;;
-					'apt' ) $pm remove $@ ;;
-				esac
-				;;
-		esac
-	}
-
-	list(){
-		case "$pmn" in
-			'pacman' ) $pmn -Q ;;
-			'emerge' ) equery list "*" ;;
-			'apt' ) dpkg-query -W | cut -f1 ;;
-		esac
-	}
-
-	count(){ list | wc -l; }
-
-	search(){
-		case "$pmn" in
-			'pacman' ) $pmn -Ss $1 || aur s $1 ;;
-			'emerge' ) $pm --search $1 ;;
-			'apt' ) $pmn search $1 ;;
-		esac
-	}
-
 	rank_servers(){
 		if [ $is_rate_mirrors -eq 1 ]; then
 			read -p "Would you like install rate-mirrors [y/N]? " ans
@@ -213,32 +234,31 @@ else
 		esac
 	}
 
-	remove_zombies(){
-		case "$pmn" in
-			'pacman' ) $pm -Rns $($pm -Qtdq) ;;
-			'emerge' ) gentoo_stuff nu && $pm --depclean ;;
-			'apt' ) $pm autoremove ;;
-		esac
-	}
-
-	edit_conf(){
-		case "$pmn" in
-			'pacman' ) $PERM $EDITOR /etc/pacman.conf ;;
-			'emerge' ) $PERM $EDITOR /etc/portage/make.conf ;;
-			'apt' ) $PERM $EDITOR /etc/apt/sources.list ;;
-		esac
-	}
-
-	auto_install_uninstall(){
-		for p in $@; do
-			if list | grep -q "$p"; then
-				to_uninstall="$to_uninstall $p"
-			else
-				to_install="$to_install $p"
-			fi
-		done
-		[ -n "$to_install" ] && install $to_install
-		[ -n "$to_uninstall" ] && uninstall $to_uninstall
+	win_list(){ $win list | tail -n +3 | grep -e 'msstore' -e 'winget'; }
+	windows_stuff(){
+		if [ $is_win -eq 0 ]; then
+			case $1 in	
+				i )
+					shift;
+					for w in $@; do
+						$win install $w
+					done
+					;;
+				r ) 
+					shift;
+					for w in $@; do
+						$win uninstall $w
+					done
+					;;
+				u ) $win upgrade ;;
+				s ) $win search $2 ;;
+				l ) win_list ;;
+				c ) win_list | wc -l ;;
+			esac
+		else
+			echo "$win not found"	
+			exit 1
+		fi
 	}
 
 	if ! exist $viewer; then
@@ -254,26 +274,13 @@ else
 		i | install ) shift; install $@ ;;
 		r | rm ) shift; uninstall $@ ;;
 		u | update ) update ;;
-		l | list ) list | $viewer | cut -d ' ' -f 1 | tr -d '\n' | xclip -sel c ;;
+		l | list ) list | $viewer | cut -d ' ' -f 1 | tr -d '\n' | yoink ;;
 		c | count ) count ;;
 		rmz ) remove_zombies ;;
 		e | edit ) edit_conf ;;
 		s | search ) shift; search $1 ;;
 		ex | exist ) shift; exist $1 ;;
-		# arch stuff
-		rs ) rank_servers ;;
-		ai ) shift; aur i $@ ;;
-		ae ) aur e ;;
-		as ) shift; aur s $@ ;;
-		# gentoo stuff
-		nu ) gentoo_stuff nu ;;
-		cu ) gentoo_stuff cu ;;
-		ct ) shift; gentoo_stuff $1 ;;
-		ar ) shift; gentoo_stuff $1 ;;
-		dr ) shift; gentoo_stuff $1 ;;
-		um ) shfit; gentoo_stuff $1 ;;
-		# ubuntu stuff
-		du ) shift; ubuntu_stuff du;;
+
 		# flatpak
 		fi ) shift; flatpak_stuff i $@ ;;
 		fr ) shift; flatpak_stuff r $@ ;;
@@ -283,6 +290,31 @@ else
 		fc ) flatpak_stuff c ;;
 		fs ) shift; flatpak_stuff s $@ ;;
 		frmz ) shift; flatpak_stuff rmz ;;
+
+		# arch stuff
+		rs ) rank_servers ;;
+		ai ) shift; aur i $@ ;;
+		ae ) aur e ;;
+		as ) shift; aur s $@ ;;
+
+		# gentoo stuff
+		nu ) gentoo_stuff nu ;;
+		cu ) gentoo_stuff cu ;;
+		ct ) shift; gentoo_stuff $1 ;;
+		ar ) shift; gentoo_stuff $1 ;;
+		dr ) shift; gentoo_stuff $1 ;;
+		um ) shfit; gentoo_stuff $1 ;;
+
+		# ubuntu stuff
+		du ) shift; ubuntu_stuff du;;
+
+		# windows stuff
+		wi ) shift; windows_stuff i $@ ;;
+		wr ) shift; windows_stuff r $@ ;;
+		wu ) windows_stuff u ;;
+		ws ) shift; windows_stuff $1 ;;
+		wl ) windows_stuff l | $viewer ;;
+		wc ) windows_stuff c ;;
 		* ) auto_install_uninstall $@ ;;
 	esac
 fi
